In [1]:
import pandas as pd
import numpy as np

In [75]:
df = pd.read_csv('D:\Rprojects\\research_data_synthesis\\Mar23.csv', header=0, index_col=0)
df

,test_f1_macro_end,test_f1_macro_end.1,test_f1_macro_end.2,test_f1_macro_end.3,test_f1_macro_end.4,test_f1_macro_end.5,test_f1_macro_end.6,test_f1_macro_end.7,test_f1_macro_end.8,test_f1_macro_max,...,test_f1_micro_end.8,test_f1_micro_max,test_f1_micro_max.1,test_f1_micro_max.2,test_f1_micro_max.3,test_f1_micro_max.4,test_f1_micro_max.5,test_f1_micro_max.6,test_f1_micro_max.7,test_f1_micro_max.8
train_option,mix,original,original,original,synthetic,synthetic,synthetic,synthetic,synthetic,mix,...,synthetic,mix,original,original,original,synthetic,synthetic,synthetic,synthetic,synthetic
dataset_name,Adult_mix,Covertype,MNIST12,MNIST28,Adult,Census,Covertype,MNIST12,MNIST28,Adult_mix,...,MNIST28,Adult_mix,Covertype,MNIST12,MNIST28,Adult,Census,Covertype,MNIST12,MNIST28
augment_option,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
categorical,0.7347982198431702,NaN,NaN,NaN,0.7187076670888153,0.7165263753134499,0.4801810746254698,0.791463152,0.8051613021162994,0.7433453135316489,...,0.8084,0.791727903,NaN,NaN,NaN,0.7634893974385891,0.7644341801385681,0.6312401573109128,0.7957,0.8136
compare_sdv_categorical,NaN,NaN,NaN,NaN,0.7170661259844104,0.7170731252988158,0.4798331316582189,0.7961158189656352,0.8069919844070228,NaN,...,0.8084,NaN,NaN,NaN,NaN,0.7624396388830569,0.7606550493386521,0.6316876500606697,0.8034,0.8183
compare_sdv_gaussian,NaN,NaN,NaN,NaN,0.5979305848299343,0.599631069,0.3609857698298801,0.3978987848435641,0.3638834597293214,NaN,...,0.3788,NaN,NaN,NaN,NaN,0.7964518160823011,0.8003359227377703,0.4531380429076702,0.4868,0.4051
compare_sdv_pca_gmm,NaN,NaN,NaN,NaN,0.7172054947855945,0.7279380377241917,0.4855231191601863,0.7946713220102058,0.76696388,NaN,...,0.7685,NaN,NaN,NaN,NaN,0.7672685282385051,0.774721814,0.6941042830219529,0.8035,0.7781
compare_sdv_rf,NaN,NaN,NaN,NaN,0.7424405782154562,0.7482532033108433,0.6303536041873461,0.873409404,0.8711462608676582,NaN,...,0.8706,NaN,NaN,NaN,NaN,0.8410665546924208,0.8422212891035062,0.7808920595853808,0.8766,0.8744
compare_sdv_tvae_categoricalNB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8093031026565743,0.8285627200954797,NaN,...,0.831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8154,0.8347
compare_sdv_tvae_gaussianNB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3980041428599746,0.4371185760014226,NaN,...,0.5138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4778,0.5165
compare_sdv_tvae_pca_gmm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8104642601352893,0.8304517528435943,NaN,...,0.833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.816,0.8343
compare_sdv_tvae_rf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9323312900535364,0.9460543310484828,NaN,...,0.9465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9334,0.9486
compare_sdv_tvae_xgb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9429362235836736,0.9598570628761118,NaN,...,0.9601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9452,0.9612
compare_sdv_xgb,NaN,NaN,NaN,NaN,0.6884643658748745,0.728075274,0.5925999127376259,0.8754956119144719,0.8608293168606955,NaN,...,0.855,NaN,NaN,NaN,NaN,0.839806844,0.8418013856812933,0.7678459248040068,0.8779,0.867
ctgan,0.7798523671447183,NaN,NaN,NaN,0.7690919815680533,0.7598101739997537,0.4748430987470255,0.4703916885190288,0.3916204066192958,0.7869957962018506,...,0.4077,0.8498845265588915,NaN,NaN,NaN,0.8328784379592694,0.8260550073483098,0.6803783034861406,0.5544,0.5341
gaussian,0.6655876388468094,NaN,NaN,NaN,0.5681211657622532,0.6345683180015191,0.3573125747419766,0.3054183029267149,0.4723245548384792,0.6655876388468094,...,0.4939,0.8112534117153055,NaN,NaN,NaN,0.7831198824270418,0.801595633,0.4441795822827293,0.3885,0.5075
none,NaN,0.9067320812111248,0.9589100035025108,0.977846374,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.9400445771623795,0.9601,0.9792,NaN,NaN,NaN,NaN,NaN
pca_gmm,0.750671679,NaN,NaN,NaN,0.7178603513405275,0.7352284277385774,0.4678613556494798,0.7829122790243647,0.7841584049272095,0.7668110871760498,...,0.7866,0.8339281965148015,NaN,NaN,NaN,0.8252152005038841,0.8289943313038002,0.7050592497611937,0.7878,0.801
rf,0.7746396429611135,NaN,NaN,NaN,0.7579927197504357,0.7456012588668144,0.6414576890135034,0.8816215572486479,0.8587534287735108,0.7843907765473556,...,0.8586,0.8466302750367416,NaN,NaN,NaN,0.8408566029813143,0.8418013856812933,0.7947,0.8836,0.8675
sdv_tvae_categorical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8140095282736771,0.828504185,NaN,...,0.8309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8193,0.8333
sdv_tvae_gaussian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4021400270662401,0.4465836996680165,NaN,...,0.5223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4785,0.5236
sdv_tvae_pca_gmm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.813437075,0.8301156173304616,NaN,...,0.8324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8183,0.8349
sdv_tvae_rf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9302460860266192,0.9469810668217504,NaN,...,0.9474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9318,0.9482
sdv_tvae_xgb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9396494007184604,0.9609658054022924,NaN,...,0.9612,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9407,0.9619
tvae,NaN,NaN,NaN,NaN,0.7177808494069435,0.7222924020703038,0.2672459195051856,0.9216899968362328,0.9289449422883832,NaN,...,0.9291,NaN,NaN,NaN,NaN,0.8167121562040731,0.8144026873819021,0.6526423586310164,0.9252,0.9361
xgb,0.7732502421510552,NaN,NaN,NaN,0.7374930147509772,0.7280140604893692,0.6346473583140428,0.8787915436373581,0.8727587442749101,0.7771508611456992,...,0.8712,0.8480999370144867,NaN,NaN,NaN,0.8406466512702079,0.8434809993701449,0.7808,0.8803,0.8793

In [2]:
def filter_by_train_option(df, train_option):
    # keep only columns that have the row 'train_option' == train_option
    # train_option are 'original', 'synthetic', 'mix'

    select_cols = df.loc['train_option'].eq(train_option)
    # select_cols['Unnamed: 0'] = True    
    return df.loc[:, select_cols]

In [77]:
df_synthetic = filter_by_train_option(df, 'synthetic')
df_synthetic

,test_f1_macro_end.4,test_f1_macro_end.5,test_f1_macro_end.6,test_f1_macro_end.7,test_f1_macro_end.8,test_f1_macro_max.4,test_f1_macro_max.5,test_f1_macro_max.6,test_f1_macro_max.7,test_f1_macro_max.8,test_f1_micro_end.4,test_f1_micro_end.5,test_f1_micro_end.6,test_f1_micro_end.7,test_f1_micro_end.8,test_f1_micro_max.4,test_f1_micro_max.5,test_f1_micro_max.6,test_f1_micro_max.7,test_f1_micro_max.8
train_option,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic
dataset_name,Adult,Census,Covertype,MNIST12,MNIST28,Adult,Census,Covertype,MNIST12,MNIST28,Adult,Census,Covertype,MNIST12,MNIST28,Adult,Census,Covertype,MNIST12,MNIST28
augment_option,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
categorical,0.7187076670888153,0.7165263753134499,0.4801810746254698,0.791463152,0.8051613021162994,0.7187076670888153,0.7187288961250002,0.4803481342357591,0.7949670962628057,0.8104945617915569,0.7630694940163762,0.7595003149275666,0.6309647771572162,0.7922,0.8084,0.7634893974385891,0.7644341801385681,0.6312401573109128,0.7957,0.8136
compare_sdv_categorical,0.7170661259844104,0.7170731252988158,0.4798331316582189,0.7961158189656352,0.8069919844070228,0.7184464297183154,0.718724086,0.4805055294556291,0.7990654773892916,0.8168666543037244,0.7608650010497585,0.7589754356498005,0.6312229460513068,0.8007,0.8084,0.7624396388830569,0.7606550493386521,0.6316876500606697,0.8034,0.8183
compare_sdv_gaussian,0.5979305848299343,0.599631069,0.3609857698298801,0.3978987848435641,0.3638834597293214,0.6298398821077321,0.6410265615489957,0.3651602464704934,0.4018261464037401,0.4015969845857017,0.7855343271047659,0.7862691580936385,0.4508231284906586,0.4826,0.3788,0.7964518160823011,0.8003359227377703,0.4531380429076702,0.4868,0.4051
compare_sdv_pca_gmm,0.7172054947855945,0.7279380377241917,0.4855231191601863,0.7946713220102058,0.76696388,0.7335438573780975,0.7385048971654855,0.4977414989490513,0.799049102,0.7768115553102355,0.746903212,0.7608650010497585,0.6879770746022048,0.7994,0.7685,0.7672685282385051,0.774721814,0.6941042830219529,0.8035,0.7781
compare_sdv_rf,0.7424405782154562,0.7482532033108433,0.6303536041873461,0.873409404,0.8711462608676582,0.7687176324771305,0.7743844958620149,0.6304821161853542,0.8750969956702879,0.8749029796028042,0.8359227377703128,0.834138148,0.7799196234176399,0.8749,0.8706,0.8410665546924208,0.8422212891035062,0.7808920595853808,0.8766,0.8744
compare_sdv_tvae_categoricalNB,NaN,NaN,NaN,0.8093031026565743,0.8285627200954797,NaN,NaN,NaN,0.8129681964715146,0.8322378836697109,NaN,NaN,NaN,0.812,0.831,NaN,NaN,NaN,0.8154,0.8347
compare_sdv_tvae_gaussianNB,NaN,NaN,NaN,0.3980041428599746,0.4371185760014226,NaN,NaN,NaN,0.4038516591998338,0.4407853126919483,NaN,NaN,NaN,0.4731,0.5138,NaN,NaN,NaN,0.4778,0.5165
compare_sdv_tvae_pca_gmm,NaN,NaN,NaN,0.8104642601352893,0.8304517528435943,NaN,NaN,NaN,0.8134890539953397,0.831846886,NaN,NaN,NaN,0.813,0.833,NaN,NaN,NaN,0.816,0.8343
compare_sdv_tvae_rf,NaN,NaN,NaN,0.9323312900535364,0.9460543310484828,NaN,NaN,NaN,0.9330500265880256,0.9481754792743964,NaN,NaN,NaN,0.9327,0.9465,NaN,NaN,NaN,0.9334,0.9486
compare_sdv_tvae_xgb,NaN,NaN,NaN,0.9429362235836736,0.9598570628761118,NaN,NaN,NaN,0.9449140713758448,0.9610001411003516,NaN,NaN,NaN,0.9432,0.9601,NaN,NaN,NaN,0.9452,0.9612
compare_sdv_xgb,0.6884643658748745,0.728075274,0.5925999127376259,0.8754956119144719,0.8608293168606955,0.7692390179912588,0.7734106448478515,0.6037591743818826,0.8770008373139151,0.8707822087272559,0.8104136048708797,0.8244803695150116,0.7671574744197655,0.8766,0.855,0.839806844,0.8418013856812933,0.7678459248040068,0.8779,0.867
ctgan,0.7690919815680533,0.7598101739997537,0.4748430987470255,0.4703916885190288,0.3916204066192958,0.7761298938352998,0.7733715607676727,0.4835195285184258,0.4815952377192015,0.4453581081026362,0.8189166491706907,0.8095737980264539,0.6764025025171467,0.5326,0.4077,0.8328784379592694,0.8260550073483098,0.6803783034861406,0.5544,0.5341
gaussian,0.5681211657622532,0.6345683180015191,0.3573125747419766,0.3054183029267149,0.4723245548384792,0.5886325070164034,0.6541053797622616,0.3601275943805416,0.3236030574819976,0.4865010567349731,0.7777661137938274,0.7979214780600462,0.4427596533652315,0.3752,0.4939,0.7831198824270418,0.801595633,0.4441795822827293,0.3885,0.5075
none,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pca_gmm,0.7178603513405275,0.7352284277385774,0.4678613556494798,0.7829122790243647,0.7841584049272095,0.7557740442737708,0.7542975510755553,0.4792203624228391,0.787593435,0.7985447929975746,0.8104136048708797,0.8155574217929876,0.7003777871483524,0.783,0.7866,0.8252152005038841,0.8289943313038002,0.7050592497611937,0.7878,0.801
rf,0.7579927197504357,0.7456012588668144,0.6414576890135034,0.8816215572486479,0.8587534287735108,0.7760147845942743,0.7771708615522934,0.6527164450673965,0.8837177043389772,0.8675718944451896,0.8374973756036111,0.8348729792147807,0.793,0.8814,0.8586,0.8408566029813143,0.8418013856812933,0.7947,0.8836,0.8675
sdv_tvae_categorical,NaN,NaN,NaN,0.8140095282736771,0.828504185,NaN,NaN,NaN,0.8166074611458665,0.8309354815861824,NaN,NaN,NaN,0.8166,0.8309,NaN,NaN,NaN,0.8193,0.8333
sdv_tvae_gaussian,NaN,NaN,NaN,0.4021400270662401,0.4465836996680165,NaN,NaN,NaN,0.4049447098298322,0.4492458899687309,NaN,NaN,NaN,0.4757,0.5223,NaN,NaN,NaN,0.4785,0.5236
sdv_tvae_pca_gmm,NaN,NaN,NaN,0.813437075,0.8301156173304616,NaN,NaN,NaN,0.8157239140622128,0.8326137357706891,NaN,NaN,NaN,0.816,0.8324,NaN,NaN,NaN,0.8183,0.8349
sdv_tvae_rf,NaN,NaN,NaN,0.9302460860266192,0.9469810668217504,NaN,NaN,NaN,0.9314213700128904,0.9477908484801294,NaN,NaN,NaN,0.9306,0.9474,NaN,NaN,NaN,0.9318,0.9482
sdv_tvae_xgb,NaN,NaN,NaN,0.9396494007184604,0.9609658054022924,NaN,NaN,NaN,0.9403850928842428,0.9616767058547572,NaN,NaN,NaN,0.9398,0.9612,NaN,NaN,NaN,0.9407,0.9619
tvae,0.7177808494069435,0.7222924020703038,0.2672459195051856,0.9216899968362328,0.9289449422883832,0.7503944115852196,0.7383791024283467,0.2972320714416863,0.9248462943223508,0.935625921,0.807264329,0.8045349569598992,0.6439420669001661,0.9219,0.9291,0.8167121562040731,0.8144026873819021,0.6526423586310164,0.9252,0.9361
xgb,0.7374930147509772,0.7280140604893692,0.6346473583140428,0.8787915436373581,0.8727587442749101,0.7724283097243554,0.7739578363107567,0.646754193,0.8807323097061156,0.8801609984967349,0.829414235,0.8200713835817762,0.7787,0.8783,0.8712,0.8406466512702079,0.8434809993701449,0.7808,0.8803,0.8793

In [3]:
def filter_by_metric(df, metric):
    df_metric = df.filter(like=metric)
    df_metric.columns = df_metric.loc['dataset_name']
    df_metric = df_metric.drop(index=['dataset_name', 'train_option', 'augment_option', 'none', 'ctgan', 'tvae']) # drop 'dataset_name', 'train_option', 'augment_option', and 'none' rows
    df_metric = df_metric[~df_metric.index.str.contains('gauss', na=False)] # drop rows that contain 'gauss' in the index
    return df_metric

In [79]:
df_macro_max = filter_by_metric(df_synthetic, 'macro_max')
df_macro_max

dataset_name,Adult,Census,Covertype,MNIST12,MNIST28
categorical,0.7187076670888153,0.7187288961250002,0.4803481342357591,0.7949670962628057,0.8104945617915569
compare_sdv_categorical,0.7184464297183154,0.718724086,0.4805055294556291,0.7990654773892916,0.8168666543037244
compare_sdv_pca_gmm,0.7335438573780975,0.7385048971654855,0.4977414989490513,0.799049102,0.7768115553102355
compare_sdv_rf,0.7687176324771305,0.7743844958620149,0.6304821161853542,0.8750969956702879,0.8749029796028042
compare_sdv_tvae_categoricalNB,NaN,NaN,NaN,0.8129681964715146,0.8322378836697109
compare_sdv_tvae_pca_gmm,NaN,NaN,NaN,0.8134890539953397,0.831846886
compare_sdv_tvae_rf,NaN,NaN,NaN,0.9330500265880256,0.9481754792743964
compare_sdv_tvae_xgb,NaN,NaN,NaN,0.9449140713758448,0.9610001411003516
compare_sdv_xgb,0.7692390179912588,0.7734106448478515,0.6037591743818826,0.8770008373139151,0.8707822087272559
pca_gmm,0.7557740442737708,0.7542975510755553,0.4792203624228391,0.787593435,0.7985447929975746
rf,0.7760147845942743,0.7771708615522934,0.6527164450673965,0.8837177043389772,0.8675718944451896
sdv_tvae_categorical,NaN,NaN,NaN,0.8166074611458665,0.8309354815861824
sdv_tvae_pca_gmm,NaN,NaN,NaN,0.8157239140622128,0.8326137357706891
sdv_tvae_rf,NaN,NaN,NaN,0.9314213700128904,0.9477908484801294
sdv_tvae_xgb,NaN,NaN,NaN,0.9403850928842428,0.9616767058547572
xgb,0.7724283097243554,0.7739578363107567,0.646754193,0.8807323097061156,0.8801609984967349

In [80]:
df_micro_max = filter_by_metric(df_synthetic, 'micro_max')
df_micro_max

dataset_name,Adult,Census,Covertype,MNIST12,MNIST28
categorical,0.7634893974385891,0.7644341801385681,0.6312401573109128,0.7957,0.8136
compare_sdv_categorical,0.7624396388830569,0.7606550493386521,0.6316876500606697,0.8034,0.8183
compare_sdv_pca_gmm,0.7672685282385051,0.774721814,0.6941042830219529,0.8035,0.7781
compare_sdv_rf,0.8410665546924208,0.8422212891035062,0.7808920595853808,0.8766,0.8744
compare_sdv_tvae_categoricalNB,NaN,NaN,NaN,0.8154,0.8347
compare_sdv_tvae_pca_gmm,NaN,NaN,NaN,0.816,0.8343
compare_sdv_tvae_rf,NaN,NaN,NaN,0.9334,0.9486
compare_sdv_tvae_xgb,NaN,NaN,NaN,0.9452,0.9612
compare_sdv_xgb,0.839806844,0.8418013856812933,0.7678459248040068,0.8779,0.867
pca_gmm,0.8252152005038841,0.8289943313038002,0.7050592497611937,0.7878,0.801
rf,0.8408566029813143,0.8418013856812933,0.7947,0.8836,0.8675
sdv_tvae_categorical,NaN,NaN,NaN,0.8193,0.8333
sdv_tvae_pca_gmm,NaN,NaN,NaN,0.8183,0.8349
sdv_tvae_rf,NaN,NaN,NaN,0.9318,0.9482
sdv_tvae_xgb,NaN,NaN,NaN,0.9407,0.9619
xgb,0.8406466512702079,0.8434809993701449,0.7808,0.8803,0.8793

In [5]:
def calculate_average(df):
    df = df.apply(pd.to_numeric, errors='coerce')
    df['Average'] = df.mean(numeric_only=True, axis=1)
    return df

In [82]:
df_macro_max_avg = calculate_average(df_macro_max)
df_macro_max_avg

dataset_name,Adult,Census,Covertype,MNIST12,MNIST28,Average
categorical,0.718708,0.718729,0.480348,0.794967,0.810495,0.704649
compare_sdv_categorical,0.718446,0.718724,0.480506,0.799065,0.816867,0.706722
compare_sdv_pca_gmm,0.733544,0.738505,0.497741,0.799049,0.776812,0.709130
compare_sdv_rf,0.768718,0.774384,0.630482,0.875097,0.874903,0.784717
compare_sdv_tvae_categoricalNB,NaN,NaN,NaN,0.812968,0.832238,0.822603
compare_sdv_tvae_pca_gmm,NaN,NaN,NaN,0.813489,0.831847,0.822668
compare_sdv_tvae_rf,NaN,NaN,NaN,0.933050,0.948175,0.940613
compare_sdv_tvae_xgb,NaN,NaN,NaN,0.944914,0.961000,0.952957
compare_sdv_xgb,0.769239,0.773411,0.603759,0.877001,0.870782,0.778838
pca_gmm,0.755774,0.754298,0.479220,0.787593,0.798545,0.715086
rf,0.776015,0.777171,0.652716,0.883718,0.867572,0.791438
sdv_tvae_categorical,NaN,NaN,NaN,0.816607,0.830935,0.823771
sdv_tvae_pca_gmm,NaN,NaN,NaN,0.815724,0.832614,0.824169
sdv_tvae_rf,NaN,NaN,NaN,0.931421,0.947791,0.939606
sdv_tvae_xgb,NaN,NaN,NaN,0.940385,0.961677,0.951031
xgb,0.772428,0.773958,0.646754,0.880732,0.880161,0.790807

In [4]:
def add_categorical_columns(df):
    df['has_y'] = df.index.to_series().apply(lambda x: 1 if 'compare' in x or x in ['tvae', 'ctgan'] else 0)
    df['tvae'] = df.index.to_series().apply(lambda x: 1 if 'tvae' in x else 0)
    return df

In [6]:
import pandas as pd
import numpy as np
def post_process_csv(path, train_option='synthetic', metric='macro_max', to_csv=False):
    df = pd.read_csv(path, header=0, index_col=0)
    df = filter_by_train_option(df, train_option=train_option)
    df = filter_by_metric(df, metric=metric)
    df = calculate_average(df)
    df = add_categorical_columns(df)

    if to_csv:
        out_path = path.split('.csv')[0] + f"_{train_option}_{metric}.csv"
        df.to_csv(out_path)
    return df

In [9]:
for train_option in ['synthetic']:
    for metric in ['macro_max', 'micro_max']:
        post_process_csv('D:\Rprojects\\research_data_synthesis\\April02.csv', train_option, metric, True)

## new processing for multi-factor analysis

In [5]:
def add_categorical_columns2(df):
    df['has_y'] = df.index.to_series().apply(lambda x: 1 if 'compare' in x or x in ['tvae', 'ctgan'] else 0)
    df['tvae'] = df.index.to_series().apply(lambda x: 1 if 'tvae' in x else 0)
    df['approach'] = df.index.to_series().apply(lambda x: 'old' if x in ['tvae', 'ctgan'] else 'new')

    return df

In [6]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('D:\Rprojects\\research_data_synthesis\\April29.csv', header=0, index_col=0)
df

,test_f1_binary_end,test_f1_binary_end.1,test_f1_binary_end.2,test_f1_binary_end.3,test_f1_binary_end.4,test_f1_binary_max,test_f1_binary_max.1,test_f1_binary_max.2,test_f1_binary_max.3,test_f1_binary_max.4,...,test_f1_micro_max.3,test_f1_micro_max.4,test_f1_micro_max.5,test_f1_micro_max.6,test_f1_micro_max.7,test_f1_micro_max.8,test_f1_micro_max.9,test_f1_micro_max.10,test_f1_micro_max.11,test_f1_micro_max.12
train_option,mix,original,synthetic,synthetic,synthetic,mix,original,synthetic,synthetic,synthetic,...,original,original,original,original,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic
dataset_name,Adult_mix,Census_Kdd,Adult,Census,Census_Kdd,Adult_mix,Census_Kdd,Adult,Census,Census_Kdd,...,Census_Kdd,Covertype,MNIST12,MNIST28,Adult,Census,Census_Kdd,Covertype,MNIST12,MNIST28
augment_option,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
categorical,0.6261117040199218,NaN,0.6069998258749782,0.6061543751074437,0.6072246696035243,0.6319109461966604,NaN,0.6080944350758853,0.6076777414357032,0.6114991939817302,...,NaN,NaN,NaN,NaN,0.7634893974385891,0.7644341801385681,0.7723073693050598,0.6312401573109128,0.7957,0.8136
compare_sdv_categorical,NaN,NaN,0.6057459328487366,0.6081911262798635,0.6085621695377793,NaN,NaN,0.6075510910980256,0.6101231190150479,0.6096019135486076,...,NaN,NaN,NaN,NaN,0.7624396388830569,0.7606550493386521,0.76013017,0.6316876500606697,0.8034,0.8183
compare_sdv_gaussian,NaN,NaN,0.3232858562437893,0.3262739907346128,0.3205853009644163,NaN,NaN,0.3814992025518341,0.4018867924528302,0.393795505,...,NaN,NaN,NaN,NaN,0.7964518160823011,0.8003359227377703,0.7989712366155785,0.4531380429076702,0.4868,0.4051
compare_sdv_pca_gmm,NaN,NaN,0.6255629756173319,0.633290406,0.6330423537019075,NaN,NaN,0.6387485742219325,0.6421804886155892,0.6408894789246599,...,NaN,NaN,NaN,NaN,0.7672685282385051,0.774721814,0.7732521520050388,0.6941042830219529,0.8035,0.7781
compare_sdv_rf,NaN,NaN,0.5872722471613414,0.6012115093387178,0.5942915392456677,NaN,NaN,0.644044637,0.6656176239181747,0.660759494,...,NaN,NaN,NaN,NaN,0.8410665546924208,0.8422212891035062,0.842116313,0.7808920595853808,0.8766,0.8744
compare_sdv_tvae_categoricalNB,NaN,NaN,NaN,NaN,0.6044474393530997,NaN,NaN,NaN,NaN,0.6057546693589096,...,NaN,NaN,NaN,NaN,0.7543564980054588,0.7546714255721184,0.754986353,0.635,0.8154,0.8347
compare_sdv_tvae_gaussianNB,NaN,NaN,NaN,NaN,0.3319064866644715,NaN,NaN,NaN,NaN,0.3883248730964467,...,NaN,NaN,NaN,NaN,0.7981314297711526,0.7994961158933446,0.7976065504933865,0.4608,0.4778,0.5165
compare_sdv_tvae_pca_gmm,NaN,NaN,NaN,NaN,0.6132908643405242,NaN,NaN,NaN,NaN,0.6331178824253616,...,NaN,NaN,NaN,NaN,0.7613898803275246,0.756875919,0.7508922947722024,0.6802,0.816,0.8343
compare_sdv_tvae_rf,NaN,NaN,NaN,NaN,0.593904663,NaN,NaN,NaN,NaN,0.6629550321199144,...,NaN,NaN,NaN,NaN,0.8425362166701659,0.8405416754146546,0.840226748,0.7813,0.9334,0.9486
compare_sdv_tvae_xgb,NaN,NaN,NaN,NaN,0.5694154488517745,NaN,NaN,NaN,NaN,0.65532479,...,NaN,NaN,NaN,NaN,0.8409615788368675,0.8394919168591224,0.8397018685702289,0.7841,0.9452,0.9612
compare_sdv_xgb,NaN,NaN,0.4935501962983735,0.5661650233523612,0.5617154811715481,NaN,NaN,0.6442307692307693,0.660234899,0.6557235421166306,...,NaN,NaN,NaN,NaN,0.839806844,0.8418013856812933,0.8422212891035062,0.7678459248040068,0.8779,0.867
ctgan,0.6571834992887624,NaN,0.6618310135267594,0.6504816955684007,0.6620111731843575,0.6789324706833805,NaN,0.6672117743254292,0.6649361022364217,0.665055388,...,NaN,NaN,NaN,NaN,0.8328784379592694,0.8260550073483098,0.8254251522149906,0.6803783034861406,0.5544,0.5341
gaussian,0.4451970443349753,NaN,0.2672204915195569,0.3902439024390244,0.3655705996131528,0.4451970443349753,NaN,0.3057795698924731,0.4283987915407855,0.4200913242009132,...,NaN,NaN,NaN,NaN,0.7831198824270418,0.801595633,0.8013856812933026,0.4441795822827293,0.3885,0.5075
none,NaN,0.6869009584664537,NaN,NaN,NaN,NaN,0.6883322049198827,NaN,NaN,NaN,...,0.857232836,0.9400445771623795,0.9601,0.9792,NaN,NaN,NaN,NaN,NaN,NaN
pca_gmm,0.6115859449192782,NaN,0.5562653562653562,0.5893900444028979,0.5980462234929712,0.6566515837104072,NaN,0.6378400324807145,0.6203554119547657,0.6419302514193025,...,NaN,NaN,NaN,NaN,0.8252152005038841,0.8289943313038002,0.8299391140037792,0.7050592497611937,0.7878,0.801
rf,0.6498941923348225,NaN,0.6192818494835219,0.5949008498583569,0.6064614601882473,0.6738474795346834,NaN,0.6618119511672735,0.6643995749202976,0.6670789527932385,...,NaN,NaN,NaN,NaN,0.8408566029813143,0.8418013856812933,0.8415914339701869,0.7947,0.8836,0.8675
sdv_tvae_categorical,NaN,NaN,NaN,NaN,0.6042014004668222,NaN,NaN,NaN,NaN,0.6062426973794024,...,NaN,NaN,NaN,NaN,0.7536216670165862,0.7519420533277347,0.7523619567499475,0.6358,0.8193,0.8333
sdv_tvae_gaussian,NaN,NaN,NaN,NaN,0.3476842791911285,NaN,NaN,NaN,NaN,0.4052369077306733,...,NaN,NaN,NaN,NaN,0.7935124921268109,0.8009657778710897,0.799706068,0.4613,0.4785,0.5236
sdv_tvae_pca_gmm,NaN,NaN,NaN,NaN,0.617262167,NaN,NaN,NaN,NaN,0.6354462314727215,...,NaN,NaN,NaN,NaN,0.762019735,0.7592903632164603,0.757295822,0.6856,0.8183,0.8349
sdv_tvae_rf,NaN,NaN,NaN,NaN,0.5812148782445812,NaN,NaN,NaN,NaN,0.6542649727767695,...,NaN,NaN,NaN,NaN,0.8414864581146336,0.8455805164812094,0.8441108545034642,0.7806,0.9318,0.9482
sdv_tvae_xgb,NaN,NaN,NaN,NaN,0.5669630827270278,NaN,NaN,NaN,NaN,0.6571687019448214,...,NaN,NaN,NaN,NaN,0.8410665546924208,0.8446357337812304,0.8441108545034642,0.7753,0.9407,0.9619
tvae,NaN,NaN,0.5588659298414224,0.5711653615845232,0.5699745547073791,NaN,NaN,0.6350507416081187,0.597544338,0.6375047546595664,...,NaN,NaN,NaN,NaN,0.8167121562040731,0.8144026873819021,0.8096787738820072,0.6526423586310164,0.9252,0.9361
xgb,0.6461170848267622,NaN,0.5821547955772692,0.5697791164658634,0.5395373856912319,0.6590409150901891,NaN,0.6557518311072813,0.65010352,0.6647677475898335,...,NaN,NaN,NaN,NaN,0.8406466512702079,0.8434809993701449,0.8439009027923577,0.7808,0.8803,0.8793

In [8]:
df_synthetic = filter_by_train_option(df, 'synthetic')
df_synthetic

,test_f1_binary_end.2,test_f1_binary_end.3,test_f1_binary_end.4,test_f1_binary_max.2,test_f1_binary_max.3,test_f1_binary_max.4,test_f1_macro_end.7,test_f1_macro_end.8,test_f1_macro_end.9,test_f1_macro_end.10,...,test_f1_micro_end.9,test_f1_micro_end.10,test_f1_micro_end.11,test_f1_micro_end.12,test_f1_micro_max.7,test_f1_micro_max.8,test_f1_micro_max.9,test_f1_micro_max.10,test_f1_micro_max.11,test_f1_micro_max.12
train_option,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,...,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic,synthetic
dataset_name,Adult,Census,Census_Kdd,Adult,Census,Census_Kdd,Adult,Census,Census_Kdd,Covertype,...,Census_Kdd,Covertype,MNIST12,MNIST28,Adult,Census,Census_Kdd,Covertype,MNIST12,MNIST28
augment_option,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
categorical,0.6069998258749782,0.6061543751074437,0.6072246696035243,0.6080944350758853,0.6076777414357032,0.6114991939817302,0.7187076670888153,0.7165263753134499,0.7202976902626278,0.4801810746254698,...,0.7660088179718665,0.6309647771572162,0.7922,0.8084,0.7634893974385891,0.7644341801385681,0.7723073693050598,0.6312401573109128,0.7957,0.8136
compare_sdv_categorical,0.6057459328487366,0.6081911262798635,0.6085621695377793,0.6075510910980256,0.6101231190150479,0.6096019135486076,0.7170661259844104,0.7170731252988158,0.7172767629855854,0.4798331316582189,...,0.7590804115053538,0.6312229460513068,0.8007,0.8084,0.7624396388830569,0.7606550493386521,0.76013017,0.6316876500606697,0.8034,0.8183
compare_sdv_gaussian,0.3232858562437893,0.3262739907346128,0.3205853009644163,0.3814992025518341,0.4018867924528302,0.393795505,0.5979305848299343,0.599631069,0.5966279574314135,0.3609857698298801,...,0.7855343271047659,0.4508231284906586,0.4826,0.3788,0.7964518160823011,0.8003359227377703,0.7989712366155785,0.4531380429076702,0.4868,0.4051
compare_sdv_pca_gmm,0.6255629756173319,0.633290406,0.6330423537019075,0.6387485742219325,0.6421804886155892,0.6408894789246599,0.7172054947855945,0.7279380377241917,0.7283041707884634,0.4855231191601863,...,0.7617048078941844,0.6879770746022048,0.7994,0.7685,0.7672685282385051,0.774721814,0.7732521520050388,0.6941042830219529,0.8035,0.7781
compare_sdv_rf,0.5872722471613414,0.6012115093387178,0.5942915392456677,0.644044637,0.6656176239181747,0.660759494,0.7424405782154562,0.7482532033108433,0.7445281070104595,0.6303536041873461,...,0.8328784379592694,0.7799196234176399,0.8749,0.8706,0.8410665546924208,0.8422212891035062,0.842116313,0.7808920595853808,0.8766,0.8744
compare_sdv_tvae_categoricalNB,NaN,NaN,0.6044474393530997,NaN,NaN,0.6057546693589096,0.7128734645945641,0.7121166376799553,0.7127147230312312,0.490489877,...,0.7535166911610329,0.6347,0.812,0.831,0.7543564980054588,0.7546714255721184,0.754986353,0.635,0.8154,0.8347
compare_sdv_tvae_gaussianNB,NaN,NaN,0.3319064866644715,NaN,NaN,0.3883248730964467,0.6002747859716371,0.6003994756881593,0.6026063810156576,0.3733258450846893,...,0.787003989,0.4586,0.4731,0.5138,0.7981314297711526,0.7994961158933446,0.7976065504933865,0.4608,0.4778,0.5165
compare_sdv_tvae_pca_gmm,NaN,NaN,0.6132908643405242,NaN,NaN,0.6331178824253616,0.7052208652116598,0.7004852002408257,0.6966824844551529,0.3975439148479092,...,0.71960949,0.6692,0.813,0.833,0.7613898803275246,0.756875919,0.7508922947722024,0.6802,0.816,0.8343
compare_sdv_tvae_rf,NaN,NaN,0.593904663,NaN,NaN,0.6629550321199144,0.745627614,0.7520767058893754,0.7457132594898384,0.5493244915691269,...,0.8363426411925258,0.7813,0.9327,0.9465,0.8425362166701659,0.8405416754146546,0.840226748,0.7813,0.9334,0.9486
compare_sdv_tvae_xgb,NaN,NaN,0.5694154488517745,NaN,NaN,0.65532479,0.7310692897125062,0.7298005193162309,0.7305027309961896,0.6239965758382997,...,0.8267898383371824,0.782,0.9432,0.9601,0.8409615788368675,0.8394919168591224,0.8397018685702289,0.7841,0.9452,0.9612
compare_sdv_xgb,0.4935501962983735,0.5661650233523612,0.5617154811715481,0.6442307692307693,0.660234899,0.6557235421166306,0.6884643658748745,0.728075274,0.7258275330732971,0.5925999127376259,...,0.8240604660927987,0.7671574744197655,0.8766,0.855,0.839806844,0.8418013856812933,0.8422212891035062,0.7678459248040068,0.8779,0.867
ctgan,0.6618310135267594,0.6504816955684007,0.6620111731843575,0.6672117743254292,0.6649361022364217,0.665055388,0.7690919815680533,0.7598101739997537,0.7706779512645434,0.4748430987470255,...,0.8221709006928406,0.6764025025171467,0.5326,0.4077,0.8328784379592694,0.8260550073483098,0.8254251522149906,0.6803783034861406,0.5544,0.5341
gaussian,0.2672204915195569,0.3902439024390244,0.3655705996131528,0.3057795698924731,0.4283987915407855,0.4200913242009132,0.5681211657622532,0.6345683180015191,0.6210925098379244,0.3573125747419766,...,0.7934075162712576,0.4427596533652315,0.3752,0.4939,0.7831198824270418,0.801595633,0.8013856812933026,0.4441795822827293,0.3885,0.5075
none,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pca_gmm,0.5562653562653562,0.5893900444028979,0.5980462234929712,0.6378400324807145,0.6203554119547657,0.6419302514193025,0.7178603513405275,0.7352284277385774,0.7422408835404943,0.4678613556494798,...,0.8229057316817132,0.7003777871483524,0.783,0.7866,0.8252152005038841,0.8289943313038002,0.8299391140037792,0.7050592497611937,0.7878,0.801
rf,0.6192818494835219,0.5949008498583569,0.6064614601882473,0.6618119511672735,0.6643995749202976,0.6670789527932385,0.7579927197504357,0.7456012588668144,0.7520767058893754,0.6414576890135034,...,0.8376023514591644,0.793,0.8814,0.8586,0.8408566029813143,0.8418013856812933,0.8415914339701869,0.7947,0.8836,0.8675
sdv_tvae_categorical,NaN,NaN,0.6042014004668222,NaN,NaN,0.6062426973794024,0.7119700527820051,0.7107402488555818,0.7111707170864829,0.487556135,...,0.7507873189166492,0.6351,0.8166,0.8309,0.7536216670165862,0.7519420533277347,0.7523619567499475,0.6358,0.8193,0.8333
sdv_tvae_gaussian,NaN,NaN,0.3476842791911285,NaN,NaN,0.4052369077306733,0.5927665214670166,0.6198234694351733,0.6112874042020949,0.3759357247832753,...,0.7900482888935545,0.4591,0.4757,0.5223,0.7935124921268109,0.8009657778710897,0.799706068,0.4613,0.4785,0.5236
sdv_tvae_pca_gmm,NaN,NaN,0.617262167,NaN,NaN,0.6354462314727215,0.7167552354977896,0.7055690671344098,0.7023948580499315,0.4203120485121766,...,0.7267478479949612,0.6686,0.816,0.8324,0.762019735,0.7592903632164603,0.757295822,0.6856,0.8183,0.8349
sdv_tvae_rf,NaN,NaN,0.5812148782445812,NaN,NaN,0.6542649727767695,0.7382145513145162,0.7450013875541358,0.7395137401343703,0.5522071596652971,...,0.8357127860592064,0.7742,0.9306,0.9474,0.8414864581146336,0.8455805164812094,0.8441108545034642,0.7806,0.9318,0.9482
sdv_tvae_xgb,NaN,NaN,0.5669630827270278,NaN,NaN,0.6571687019448214,0.7303360029130026,0.7282080396366846,0.7311055554434305,0.5733181056124511,...,0.8313038,0.7731,0.9398,0.9612,0.8410665546924208,0.8446357337812304,0.8441108545034642,0.7753,0.9407,0.9619
tvae,0.5588659298414224,0.5711653615845232,0.5699745547073791,0.6350507416081187,0.597544338,0.6375047546595664,0.7177808494069435,0.7222924020703038,0.7218804812371846,0.2672459195051856,...,0.8048498845265589,0.6439420669001661,0.9219,0.9291,0.8167121562040731,0.8144026873819021,0.8096787738820072,0.6526423586310164,0.9252,0.9361
xgb,0.5821547955772692,0.5697791164658634,0.5395373856912319,0.6557518311072813,0.65010352,0.6647677475898335,0.7374930147509772,0.7280140604893692,0.7139450330047394,0.6346473583140428,...,0.8202813352928826,0.7787,0.8783,0.8712,0.8406466512702079,0.8434809993701449,0.8439009027923577,0.7808,0.8803,0.8793

In [7]:
metric = 'macro_max'
df_metric = df.filter(like=metric)
df_metric.columns = df_metric.loc['dataset_name']
df_metric = df_metric.drop(index=['dataset_name', 'train_option', 'augment_option', 'none']) # drop 'dataset_name', 'train_option', 'augment_option', and 'none' rows
# drop all columns with NaN values
df_metric = df_metric.dropna(axis=1) # drop columns with all NaN values
df_metric = add_categorical_columns2(df_metric)


# 2. Bring the row‐index (method names) into a column
df_clean = df_metric.reset_index().rename(columns={'index':'method'})

# 3. Melt into long form
long_df = df_clean.melt(
    id_vars=['method', 'has_y', 'tvae', 'approach'],
    value_vars=[c for c in df_clean.columns 
                if c not in ('method','has_y','tvae')],
    var_name='dataset',
    value_name='macro_max'
)

# 4. (Optional) cast your flags to categorical
long_df['has_y'] = long_df['has_y'].astype('category')
long_df['tvae']  = long_df['tvae'].astype('category')
long_df['method'] = long_df['method'].astype('category')
long_df['dataset'] = long_df['dataset'].astype('category')

long_df

                      method has_y tvae approach  dataset           macro_max
0                categorical     0    0      new    Adult  0.7187076670888153
1    compare_sdv_categorical     1    0      new    Adult  0.7184464297183154
2       compare_sdv_gaussian     1    0      new    Adult  0.6298398821077321
3        compare_sdv_pca_gmm     1    0      new    Adult  0.7335438573780975
4             compare_sdv_rf     1    0      new    Adult  0.7687176324771305
..                       ...   ...  ...      ...      ...                 ...
127         sdv_tvae_pca_gmm     0    1      new  MNIST28  0.8326137357706891
128              sdv_tvae_rf     0    1      new  MNIST28  0.9477908484801294
129             sdv_tvae_xgb     0    1      new  MNIST28  0.9616767058547572
130                     tvae     1    1      old  MNIST28         0.935625921
131                      xgb     0    0      new  MNIST28  0.8801609984967349

[132 rows x 6 columns]

In [8]:
match_list = ['categorical', 'pca_gmm', 'gauss', 'rf', 'xgb', 'tvae', 'ctgan']
long_df['y_synth'] = long_df['method'].apply(lambda m: next((val for val in match_list if val in m), None))

long_df['y_synth'] = long_df['y_synth'].astype('category')
long_df

,method,has_y,tvae,approach,dataset,macro_max,y_synth
0,categorical,0,0,new,Adult,0.7187076670888153,categorical
1,compare_sdv_categorical,1,0,new,Adult,0.7184464297183154,categorical
2,compare_sdv_gaussian,1,0,new,Adult,0.6298398821077321,gauss
3,compare_sdv_pca_gmm,1,0,new,Adult,0.7335438573780975,pca_gmm
4,compare_sdv_rf,1,0,new,Adult,0.7687176324771305,rf
...,...,...,...,...,...,...,...
127,sdv_tvae_pca_gmm,0,1,new,MNIST28,0.8326137357706891,pca_gmm
128,sdv_tvae_rf,0,1,new,MNIST28,0.9477908484801294,rf
129,sdv_tvae_xgb,0,1,new,MNIST28,0.9616767058547572,xgb
130,tvae,1,1,old,MNIST28,0.935625921,tvae
131,xgb,0,0,new,MNIST28,0.8801609984967349,xgb

In [9]:
long_df.to_csv('D:\Rprojects\\research_data_synthesis\\April29_macro_max_mfa.csv', index=False)

In [10]:
# drop rows that contain 'gauss' in the method column
long_df_no_gauss = long_df[~long_df['method'].str.contains('gauss', na=False)]

long_df_no_gauss.to_csv('D:\Rprojects\\research_data_synthesis\\April29_macro_max_mfa_no_gauss.csv', index=False)
long_df_no_gauss

,method,has_y,tvae,approach,dataset,macro_max,y_synth
0,categorical,0,0,new,Adult,0.7187076670888153,categorical
1,compare_sdv_categorical,1,0,new,Adult,0.7184464297183154,categorical
3,compare_sdv_pca_gmm,1,0,new,Adult,0.7335438573780975,pca_gmm
4,compare_sdv_rf,1,0,new,Adult,0.7687176324771305,rf
5,compare_sdv_tvae_categoricalNB,1,1,new,Adult,0.713755799,categorical
...,...,...,...,...,...,...,...
127,sdv_tvae_pca_gmm,0,1,new,MNIST28,0.8326137357706891,pca_gmm
128,sdv_tvae_rf,0,1,new,MNIST28,0.9477908484801294,rf
129,sdv_tvae_xgb,0,1,new,MNIST28,0.9616767058547572,xgb
130,tvae,1,1,old,MNIST28,0.935625921,tvae
131,xgb,0,0,new,MNIST28,0.8801609984967349,xgb